import Link from "next/link";
import { PageHeader } from "@/components/shared/page-header";
import { createClient } from "@/lib/supabase/server";
import {
	Card,
	CardContent,
	Table,
	TableBody,
	TableCell,
	TableHead,
	TableHeader,
	TableRow,
	Button,
	Badge,
} from "@/components/ui";
import { formatCurrency } from "@/lib/utils/formatters";
import { PasswordResetButton } from "@/components/advisors/password-reset-button";

export default async function AdvisorsAnalyticsPage() {
	const supabase = await createClient();
	if (!supabase) {
		return (
			<div className="p-8 text-center text-zinc-500">
				Database connection failed
			</div>
		);
	}

	const { data: advisors } = await supabase
		.from("advisors")
		.select("id, name, code, phone, is_active")
		.order("name", { ascending: true });

	const advisorIds = (advisors ?? []).map((a) => a.id);

	const { data: sales } = advisorIds.length
		? await supabase
				.from("plot_sales")
				.select("advisor_id, total_sale_amount, remaining_amount")
				.in("advisor_id", advisorIds)
				.eq("is_cancelled", false)
		: { data: [] as any[] };

	const { data: comms } = advisorIds.length
		? await supabase
				.from("advisor_commissions")
				.select("advisor_id, remaining_commission, amount_paid, total_commission_amount")
				.in("advisor_id", advisorIds)
		: { data: [] as any[] };

	const salesAgg = new Map<
		string,
		{ salesCount: number; revenue: number; due: number }
	>();
	for (const s of sales ?? []) {
		const id = (s as any).advisor_id as string;
		const prev = salesAgg.get(id) ?? { salesCount: 0, revenue: 0, due: 0 };
		prev.salesCount += 1;
		prev.revenue += Number((s as any).total_sale_amount ?? 0);
		prev.due += Number((s as any).remaining_amount ?? 0);
		salesAgg.set(id, prev);
	}

	const commAgg = new Map<
		string,
		{ pending: number; paid: number; total: number }
	>();
	for (const c of comms ?? []) {
		const id = (c as any).advisor_id as string;
		const prev = commAgg.get(id) ?? { pending: 0, paid: 0, total: 0 };
		prev.pending += Number((c as any).remaining_commission ?? 0);
		prev.paid += Number((c as any).amount_paid ?? 0);
		prev.total += Number((c as any).total_commission_amount ?? 0);
		commAgg.set(id, prev);
	}

	return (
		<div className="space-y-6">
			<PageHeader
				title="Advisor Analytics"
				subtitle="Sales, dues, and commission status by advisor"
				action={
					<Link href="/advisors">
						<Button size="sm" variant="outline">
							Manage Advisors
						</Button>
					</Link>
				}
			/>

			<Card>
				<CardContent className="p-0 overflow-x-auto">
					<Table>
						<TableHeader>
							<TableRow>
								<TableHead>Advisor</TableHead>
								<TableHead>Phone</TableHead>
								<TableHead>Status</TableHead>
								<TableHead className="text-right">Sales</TableHead>
								<TableHead className="text-right">Revenue generated by</TableHead>
								<TableHead className="text-right">Customer Due (Net)</TableHead>
								<TableHead className="text-right">Commission Pending</TableHead>
								<TableHead className="text-right">Password</TableHead>
								<TableHead className="text-right">Open</TableHead>
							</TableRow>
						</TableHeader>
						<TableBody>
							{(advisors ?? []).length === 0 ? (
								<TableRow>
									<TableCell colSpan={9} className="py-10 text-center text-sm text-zinc-500">
										No advisors yet.
									</TableCell>
								</TableRow>
							) : (
								(advisors ?? []).map((a: any) => {
									const s = salesAgg.get(a.id) ?? { salesCount: 0, revenue: 0, due: 0 };
									const c = commAgg.get(a.id) ?? { pending: 0, paid: 0, total: 0 };
									const netRevenue = s.revenue - c.total;
									const netDue = s.due - c.pending;
									return (
										<TableRow key={a.id} className="hover:bg-zinc-50">
											<TableCell>
												<div className="flex flex-col">
													<span className="font-semibold">{a.name}</span>
													<span className="text-xs text-zinc-500 font-mono">{a.code}</span>
												</div>
											</TableCell>
											<TableCell>{a.phone}</TableCell>
											<TableCell>
												<Badge
													variant="outline"
													className={
														a.is_active
															? "bg-green-50 text-green-700 border-green-200"
															: "bg-zinc-50 text-zinc-500 border-zinc-200"
													}
												>
													{a.is_active ? "Active" : "Inactive"}
												</Badge>
											</TableCell>
											<TableCell className="text-right font-semibold">{s.salesCount}</TableCell>
											<TableCell className="text-right font-semibold">
												<div>
													<div>{formatCurrency(netRevenue)}</div>
													<div className="text-[11px] text-zinc-500 mt-0.5">
														Plot price {formatCurrency(s.revenue)} − Commission {formatCurrency(c.total)}
													</div>
												</div>
											</TableCell>
											<TableCell
												className={`text-right font-semibold ${netDue >= 0 ? "text-red-600" : "text-green-700"}`}
											>
												<div>
													<div>{formatCurrency(netDue)}</div>
													<div className="text-[11px] text-zinc-500 mt-0.5">
														Due {formatCurrency(s.due)} - Commission Pending {formatCurrency(c.pending)}
													</div>
												</div>
											</TableCell>
											<TableCell className="text-right font-semibold text-amber-700">{formatCurrency(c.pending)}</TableCell>
											<TableCell className="text-right">
												<PasswordResetButton advisorId={a.id} advisorPhone={a.phone} />
											</TableCell>
											<TableCell className="text-right">
												<Link href={`/advisors/${a.id}`}>
													<Button size="sm" variant="outline" className="h-8">
														View
													</Button>
												</Link>
											</TableCell>
										</TableRow>
									);
								})
							)}
						</TableBody>
					</Table>
				</CardContent>
			</Card>
		</div>
	);
}

